services:
  caddy:
    image: ${CADDY_IMAGE}
    restart: unless-stopped
    container_name: ${CADDY_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./static:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  default:
    name: main
    external: true
